# -*- coding: utf-8 -*-
#+TITLE: Freenet利用の手引き
#+AUTHOR: Hideki Saito
#+LANGUAGE: ja

* Freenetとは
FreenetとはIan Clerke氏によりデザインされた検閲に耐性を持たせることを目的に開始された分散型ファイル保管システムです。基礎となる機能として、ファイルをシステムに挿入する人、そして取り出す人の特定を困難1にする仕組みを備えます。
* Freenetの機能概要
** Freenetのファイル保管の特徴
Freenetではファイルは接続するノードに分散されてアップロードされます。アップロードは他のノードを経由して行います。ファイルの断片は多数のノードに拡散され保存されます。それぞれの断片は暗号化されているため、対応する鍵により参照されない限りは内容はノード自身もわかりません。
ファイルを取り出す場合は他のノードを経由してダウンロードします。この場合、多数のノードが相互的に通信しながら目的のファイルの断片を持っているノードを検索していきます。この連鎖がつながって最終的に目的のファイルが再構成されるわけですが、この長さをTTL（Time to Live）と呼びます。このTTLがある程度の長さになってもファイルが見つからない場合はそのファイルがFreenetネットワーク上に存在しないものとして処理されます。
尚、ファイルの取り出しが成功した場合、その取り出しに関与したノードはその時に得られたファイルの断片を保管することがあります。この特徴により、多くアクセスされるファイルはより高速に取り出すことができるようになり、またその信頼性も高くなることになります。反対にあまりアクセスされないキーに対応するファイルは時間が経つとアクセスが困難になっていき、やがてFreenetネットワーク上に存在しなくなります。
*** キーの種類
Freenetにはいくつかのキーが存在します。キーというのはファイルそのものを示す識別子です。分散ファイル保管システムであるFreenetはこれらのキーの組み合わせにより多数の機能を実現しています。その違いを理解することにより、Freenetのファイル保管の特性が理解しやすくなります。
**** CHKキー（内容ハッシュキー）
CHKキーというのはファイルそのものを示すキーです。この形態のキーはファイルそのもののハッシュにより生成されます。そのため、同じファイルをアップロードすると同じCHKキーが生成されます。複数人が同じファイルをアップロードした場合は、違ったCHKキーが生成されませんので、この場合、ファイルの参照可能性が高くなるにとどまります。
CHKキーの派生として、ランダム性を持たせたCHKキーを作成することができます。この場合、同じファイルをアップロードするごとにCHKキーが変わります。この場合、他人はもとより同一人物が同じファイルをアップロードする場合でも異なるCHKキーが発行されることになります。後者はアクセスが少ないファイルが失われる可能性が高くなりますが、アップロードが誰によって行われたかを特定するのがさらに困難になります。
**** SSK/USKキー（署名サブスペースキー／更新可能サブスペースキー）
USKキーはSSKキーを補完するものですが、使用上はUSKが使用されることがほとんどですので合わせて説明します。USKキーは、公開鍵暗号を使用することにより、更新可能なキーです。誰でも読むことができますが、書きこむのには秘密鍵が必要になります。これにより一度アップロードした内容を更新することができます。基本的にはFreenetで使用されるアプリケーションはそのほとんどがSSK/USKを使用しています。
**** KSKキー（キーワード署名キー）
KSKキーは使用者により指定されるキーです。KSKは任意の名前を指定することができますが、その名前を知る者が上書きすることが可能です。他の種類の鍵と違い、不特定多数の使用者が書換えられるという点において通常KSKキーが利用されることはほとんどありません。
** OpennetとDarknet
FreenetにはOpennetとDarknetの二種類の接続モードが存在します。Opennetは他のノードの探索が自動的に行われ、ネットワークを構築していく方法で、対してDarknetは信頼できるノード同士を手動で追加していくことで構築する方式となります。
Freenetは接続がDarknetに集約されることを目指してますが、実際は現実的ではなく、特にFreenetのようなシステムが禁止されていない国ではOpennetによる接続が一般的です。
尚、これらは組み合わせて使用することも可能です。
*** Opennetの特徴
Opennetでは不特定多数に対して接続をする方法で、短い時間で比較的効率の良いネットワークを構築することができます。他のFreenet使用者を知っている必要もないため、周りに使用者がいない場合でもFreenetに接続することができます。
そのぶん、誰からの接続も受け付けるという方式であるため、国により禁止されているケースなどではFreenetの接続を締め出したり、また接続を国家機関などにより恣意的に囲い込んで通信内容を捜査するといった可能性が考えられます。
*** Darknetの特徴
Darknetでは事前に信頼のできるノードを設定し、ネットワークを構築していく方法です。この特徴としては特定のノードとの接続になるため、国家機関などが閉めだすのが難しいという特徴と、不特定多数との接続ではないため、そういった機関による通信内容の傍受が難しい特徴があります。
欠点としてはFreenetを効果的に利用するためには10ノード程度を追加しておく必要があるのと、信頼できないノードを含めた場合、安全性が却って低下してしまうという問題があります。また、接続ノードの信頼性が低い場合、Freenetに接続できなくなってしまう場合があるということも考えられます。
